### ISSUE TITLE
缓存方案：非更新文章不拉取

### ISSUE THREAD

**Issue by wztlink1013** [wztlink1013/yuque-hexo-lyrics#9]
- [x] 文章如果更新了就拉取，反之不拉取
> 具体：每次拉取文章都拉去更新日期，如果每次拉取都比对，如果拉取的文章，这个文章在本地也有，就进行比对更新日期，如果一直就跳过，如果更新日期不一样则进行更新。
> 不能执行yuque-hexo-lyrics clean命令。

**Comment by CCKNBC** [comment]
先来给大佬star了，期待2.0的到来

**Comment by wztlink1013** [comment]
72462568e1e9854d518f8bff78448ce1d8db07ac
